# Generated by Django 5.2.4 on 2025-07-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('columns_count', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_values', models.JSONField(default=dict)),
                ('duplicates_count', models.IntegerField(default=0)),
                ('data_types', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_processing.uploadedfile')),
            ],
        ),
        migrations.DeleteModel(
            name='CleaningOperation',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
    ]
